nouns = ['apple', 'car', 'book', 'tree', 'dog', 'computer', 'cat', 'table', 'phone', 'chair', 
         'banana', 'house', 'pen', 'shoe', 'hat', 'shirt', 'glass', 'keyboard', 'lamp', 'bed', 
         'desk', 'mouse', 'ball', 'bag', 'bottle', 'chair', 'clock', 'door', 'flower', 'guitar', 
         'hammer', 'knife', 'light', 'mirror', 'movie', 'painting', 'pillow', 'radio', 'ring', 'shower', 
         'soap', 'sock', 'spoon', 'towel', 'train', 'umbrella', 'watch', 'window', 'airplane', 'baggage', 
         'bike', 'boat', 'bus', 'camera', 'cart', 'cellphone', 'coffee', 'cookie', 'credit card', 'dress', 
         'elevator', 'fan', 'fork', 'gift', 'glove', 'hat', 'helicopter', 'ice cream', 'jacket', 'jeans', 
         'jewelry', 'key', 'knife', 'laptop', 'letter', 'map', 'motorcycle', 'musical instrument', 'necklace', 
         'newspaper', 'pencil', 'pizza', 'purse', 'razor', 'sandwich', 'scarf', 'shirt', 'shoe', 'skateboard', 
         'ski', 'snack', 'soap', 'soda', 'spoon', 'suit', 'sunglasses', 'sweater', 'swimming pool', 't-shirt', 
         'tablet', 'taxi', 'television', 'ticket', 'tie', 'toilet', 'toy', 'truck', 'van', 'video game', 'wallet', 
         'water bottle', 'wheel', 'zipper', 'accordion', 'aircraft carrier', 'air mattress', 'airplane', 'alarm clock', 
         'album', 'alpaca', 'ambulance', 'amusement park', 'anchor', 'angel', 'ant', 'antelope', 'apartment', 
         'apple pie', 'apron', 'aquarium', 'arch', 'arm', 'armchair', 'armor', 'army', 'art gallery', 'asparagus', 
         'astronaut', 'athlete', 'atm', 'attic', 'auction', 'audio book', 'avocado', 'baby', 'backpack', 'bacon', 
         'badger', 'bagel', 'baker', 'bakery', 'balcony', 'ballerina', 'balloon', 'bamboo', 'banana bread', 'band', 
         'bank', 'bar', 'barbecue', 'barber', 'barn', 'baseball', 'basket', 'basketball', 'bat', 'bath', 'bathroom', 
         'bathtub', 'battery', 'beach', 'beagle', 'bean', 'bear', 'beard', 'bedroom', 'bee', 'beer', 'beetle', 'bell', 
         'bench', 'beret', 'bicycle', 'bigfoot', 'bike rack', 'billboard', 'binoculars', 'bird', 'birthday', 'birthday cake', 
         'blackberry', 'blackboard', 'blanket', 'blender', 'blimp', 'blind']

locations = ['beach', 'mountain', 'forest', 'park', 'island', 'river', 'lake', 'canyon', 'valley', 'desert', 
             'ocean', 'sea', 'waterfall', 'glacier', 'cave', 'volcano', 'garden', 'field', 'meadow', 'prairie', 
             'jungle', 'swamp', 'wetland', 'reef', 'coral', 'harbor', 'bay', 'cove', 'cliff', 'summit', 
             'plateau', 'coast', 'shore', 'peninsula', 'headland', 'archipelago', 'fjord', 'delta', 'estuary', 
             'channel', 'strait', 'gorge', 'gulch', 'badlands', 'bluff', 'grove', 'vineyard', 'orchard', 'cemetery', 
             'campground', 'battlefield', 'market', 'factory']

adjectives = ['abandoned', 'absent', 'accurate', 'acidic', 'active', 'adequate', 'afraid', 'agile', 'alert', 'alive',
              'ambitious', 'amused', 'ancient', 'angry', 'animated', 'anxious', 'arctic', 'aromatic', 'artificial',
              'ashamed', 'astonishing', 'athletic', 'attentive', 'attractive', 'average', 'awesome', 'awful', 'bad',
              'barren', 'beautiful', 'belated', 'belligerent', 'beneficial', 'best', 'better', 'bewitched', 'big',
              'bitter', 'black', 'bland', 'blank', 'blissful', 'blonde', 'blue', 'blushing', 'bold', 'bored',
              'boring', 'bossy', 'brave', 'breakable', 'bright', 'brilliant', 'broken', 'brown', 'bumpy', 'burly',
              'busy', 'calm', 'candid', 'canine', 'capital', 'careful', 'careless', 'caring', 'cautious', 'celestial',
              'charming', 'cheap', 'cheerful', 'chemical', 'chilly', 'chubby', 'circular', 'classic', 'clean',
              'clear', 'clever', 'clumsy', 'coarse', 'cold', 'colorful', 'colossal', 'comfortable', 'common', 'compact',
              'compassionate', 'competent', 'complete', 'complex', 'complicated', 'composed', 'concerned', 'concrete',
              'confused', 'conscious', 'considerate', 'constant', 'content', 'conventional', 'cool', 'cooperative',
              'corny', 'corrupt', 'costly', 'courageous', 'courteous', 'cowardly', 'cozy', 'crabby', 'crappy', 'crazy',
              'creative', 'creepy', 'criminal', 'crisp', 'crooked', 'crowded', 'crude', 'cruel', 'crushing', 'cuddly',
              'curious', 'curly', 'curvy', 'cute', 'dainty', 'damaged', 'damp', 'dangerous', 'dapper', 'dark',
              'dazzling', 'dead', 'deadly', 'deafening', 'dear', 'decent', 'decisive', 'deep', 'defeated', 'defiant',
              'delicate', 'delicious', 'delightful', 'demonic', 'dense', 'dependable', 'depressed', 'descriptive',
              'deserted', 'detailed', 'determined', 'devilish', 'diligent', 'dim', 'diminutive', 'dirt', 'dirty',
              'disastrous', 'discreet', 'disgusted', 'disgusting', 'dishonest', 'disloyal', 'dismal', 'distant',
              'distinct', 'distorted', 'dizzy', 'docile', 'dominant', 'dopey', 'doubtful', 'drab', 'dramatic', 'dreary',
              'droopy', 'dry', 'dual', 'dull', 'dusty', 'dutiful', 'dynamic']